openapi: 3.0.3
info:
  title: "User Greeting API"
  description: "This API greets a user by name via a simple HTTP GET request."
  version: 1.0.0

paths:
  /greet:
    get:
      summary: "Greet a user"
      description: "Returns a personalized greeting message using the provided user's name."
      operationId: greet
      parameters:
        - name: name
          in: query
          required: true
          description: "The name of the user to greet."
          schema:
            type: string
            example: "Alice"
      responses:
        '200':
          description: "Successful greeting response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "The personalized greeting message."
                    example: "Hello, Alice!"
        '400':
          description: "Bad Request - Missing or invalid name parameter"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Error message explaining the issue."
                    example: "Query parameter 'name' is required."
