openapi: 3.0.3
info:
  title: "Hotel booking API"
  description: "This API can book hotel."
  version: 1.0.0

paths:
  /book-hotel:
    get:
      summary: "Books a hotel"
      description: "Books hotel and returns bookingId"
      operationId: greet
      parameters:
        - name: hotelName
          in: query
          required: true
          description: "The name of the hotel to book."
          schema:
            type: string
            example: "Taj Mahal"
        - name: bookingDatte
          in: query
          required: true
          description: "Date of the booking"
          schema:
            type: string
            example: "9th Dec 2025"
      responses:
        '200':
          description: "Successful booking response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Booking response with booking id."
                    example: "Booking successful with id - 1076"
        '400':
          description: "Bad Request - Missing or invalid hotelName or bookingDatte parameter"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Error message explaining the issue."
                    example: "Query parameter 'name' is required."
