name: deploy-infrastructure-to-pilot

on:
  push:
    branches:
      - 'main'
    paths:
      - 'infrastructure/**'
      - '.github/workflows/pilot-deployment.yml'
      - '.github/actions/infrastructure/**'

permissions: 
  contents: read
  pull-requests: write
  checks: write
  actions: read

jobs:
  deploy-infrastructure-to-pilot:
    runs-on: ubuntu-latest
    environment:
      name: pilot
    env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_ACCOUNT_ENVIRONMENT: 'pilot'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: Cofigure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      
      - name: Set up node 23.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 23.11.0
      
      - name: Install dependencies and build infrastructure
        uses: ./.github/actions/infrastructure/build
        
      - name: Deploy infrastrcuture stack
        uses: ./.github/actions/infrastructure/stack-deployment