name: run-infrastructure-tests

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened]

permissions: 
  contents: read
  pull-requests: write
  checks: write
  actions: read

jobs:
  run-infrastructure-tests-on-pull-request:
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
        AWS_DEFAULT_REGION: 'u-east-1'
        AWS_ACCOUNT_ENVIRONMENT: 'dev'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: Cofigure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      
      - name: Set up node 23.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 23.11.0

      - name: Install dependencies and build infrastructure
        uses: ./.github/actions/infrastructure/build
  
      - name: Run unit tests on infrastructure
        shell: bash
        run: |
          cd infrastructure/
          npm run test