name: clean-up-dev-stack

on: 
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-up-dev-stack:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_DEFAULT_REGION: 'ap-south-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Set up node 23.11.0
        uses: actions/setup-node@v1
        with:
            node-version: 23.11.0

      - name: Install dependencies and build infrastructure
        uses: ./.github/actions/infrastructure/build

      - name: Delete cloudFormation stack
        run: |
          cdk destroy -c suffix="${{ github.event.pull_request.head.ref }}" --all --force